- .vscode/settings.json
- README.md
- src/config.ts
> feat: add support for loading env variable in config.yml

- src/__generated__/generated-radarr-api.ts
- src/__generated__/generated-sonarr-api.ts
- src/custom-formats.ts
- src/quality-definitions.test.ts
- src/types.ts
- src/util.test.ts
- src/util.ts
- tests/samples/20240930_cf_exceptLanguage.json
> fix: mismatch language introduced with new radarr/sonarr parameter

- index.ts
- src/quality-profiles.test.ts
- src/quality-profiles.ts
- src/types.ts
> fix: correctly implement recyclarr enabled flag for quality profiles

- src/custom-formats.ts
- src/util.test.ts
- src/util.ts
* fixes a bug where added specifications (total length > on server than what you want) have been ignored
> fix: improve comparison for custom format changes

- index.ts
- src/trash-guide.test.ts
- src/trash-guide.ts
- src/types.ts
- src/util.ts
> feat: make Trash template / QualityProfiles includable

- docs/docs/configuration/config-file.md
> docs: update docs

- src/clients/radarr-client.ts
- src/clients/readarr-client.ts
- src/clients/sonarr-client.ts
- src/clients/unified-client.ts
- src/clients/whisparr-client.ts
> fix: set new profile language to any

- src/quality-profiles.test.ts
- src/quality-profiles.ts
- tests/samples/single_custom_format.json
- tests/samples/single_quality_profile.json
* problem with 0/1 truthy values correctly handled
> fix: correctly handle diffs for minFormatScores

- examples/full/config/config.yml
- src/index.ts
> fix: use quality_defintion from main config if defined

- src/media-management.ts
- src/quality-definitions.test.ts
- src/quality-definitions.ts
- src/util.ts
Additional fix for quality sizes. See #128
> fix: preferred quality size setting

- docs/docs/configuration/config-file.md
- examples/full/config/config.yml
- examples/full/templates/radarr-cf.yml
- examples/full/templates/sonarr-cf.yml
- src/__generated__/radarr/Api.ts
- src/__generated__/radarr/data-contracts.ts
- src/__generated__/readarr/data-contracts.ts
- src/__generated__/sonarr/Api.ts
- src/__generated__/sonarr/data-contracts.ts
- src/config.test.ts
- src/config.ts
- src/custom-formats.ts
- src/index.ts
- src/media-management.ts
- src/quality-profiles.ts
- src/recyclarr-importer.ts
- src/trash-guide.ts
- src/types/common.types.ts
- src/types/config.types.ts
- src/types/helper.types.ts
- src/types/recyclarr.types.ts
- src/types/trashguide.types.ts
- src/util.ts
* adds support for trash guide naming out of the box
> feat: media naming

- docs/docs/configuration/config-file.md
- src/cache.ts
- src/index.ts
- src/quality-profiles.test.ts
- src/quality-profiles.ts
- src/trash-guide.ts
- src/types/config.types.ts
> feat: use language from TrashQPs

- docs/docs/comparison.mdx
- docs/docs/configuration/config-file.md
- docs/docs/examples.md
- examples/full/config/config.yml
- src/config.ts
- src/types/config.types.ts
> feat: add experimental support for quality profiles renaming

- docs/docs/comparison.mdx
- docs/docs/configuration/config-file.md
- docs/docs/examples.md
- examples/full/config/config.yml
- src/config.ts
- src/types/config.types.ts
> feat: add experimental support for cloning quality profiles

- src/index.ts
- src/quality-profiles.ts
> fix: use new cfs in existin g qps correctly

- docs/docs/configuration/_include/config-file-sample.yml
- docs/docs/configuration/config-file.md
- docs/docs/configuration/environment-variables.md
- examples/full/config/config.yml
- src/__generated__/ky-client.ts
- src/clients/lidarr-client.ts
- src/clients/radarr-client.ts
- src/clients/readarr-client.ts
- src/clients/sonarr-client.ts
- src/clients/unified-client.ts
- src/clients/whisparr-client.ts
- src/env.ts
- src/index.ts
- src/logger.ts
- src/types/config.types.ts
> fix: do gracefully stop instance processing if an error occurs.

- src/index.ts
> opt: improve error message logging and hint for additional stacktrace

- docs/docs/configuration/_include/config-file-sample.yml
- src/recyclarr-importer.ts
- src/trash-guide.ts
- src/types/config.types.ts
- src/util.ts
* by using sparse and filter git operations
> opt: reduce repo checkout size to <10%

- docs/docs/configuration/_include/config-file-sample.yml
- docs/docs/configuration/config-file.md
- examples/full/config/config.yml
- src/__generated__/ky-client.ts
- src/config.ts
- src/custom-formats.ts
- src/index.ts
- src/types/common.types.ts
- src/types/config.types.ts
> feat: add support for cleaning up custom formats

- .github/workflows/build.yml
- docs/docs/comparison.mdx
- docs/docs/configuration/_include/config-file-sample.yml
- docs/docs/configuration/config-file.md
- examples/full/config/config.yml
- src/config.test.ts
- src/config.ts
- src/trash-guide.test.ts
- src/trash-guide.ts
- src/types/common.types.ts
- src/types/config.types.ts
- src/types/trashguide.types.ts
> feat: add support for trash custom format groups

- docs/docs/configuration/config-file.md
- docs/docs/configuration/general.md
- examples/full/config/config.yml
- src/config.ts
- src/trash-guide.ts
* previously not the documented ordering was used
* fixes #204
> fix: correctly merge templates and configs

- docs/docs/configuration/_include/unmanaged-customformats.yml
- docs/docs/configuration/config-file.md
- src/quality-profiles.ts
> feat: support mapping custom formats on unmanaged quality profiles

- .github/workflows/build.yml
- Dockerfile
- src/env.ts
- src/index.ts
> chore: add version to container versions and output in log

- src/cache.ts
> fix: do not fail empty QualityProfiles or CustomFormats
